# Generated by Django 4.2.6 on 2024-04-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('hr', 'HR'), ('trainer', 'TRAINER'), ('manager', 'MANAGER')], max_length=20)),
            ],
        ),
    ]
