# Generated by Django 4.2.6 on 2024-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('MANAGER', 'MANAGER')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
