# Generated by Django 4.2.6 on 2024-03-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('genere', models.CharField(max_length=50)),
            ],
        ),
    ]
