# Generated by Django 4.2.6 on 2024-04-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('cloth', 'CLOTH'), ('mobile', 'MOBILE'), ('shoe', 'SHOE')], max_length=20)),
            ],
        ),
    ]
