# Generated by Django 4.2.6 on 2024-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_producttable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='image',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
