# my_file=open("demo.text","w")
# my_file.write("hello python")
# print("write operation done")
# my_file.close()

# my_file=open("demo2.text","w")
# my_file.write("12")
# print("write operation done")
# my_file.close()

# my_file=open("demo3.text","w")
# my_file.write("Hello java \n")
# my_file.write("where are you")
# print("write operation done")
# my_file.close()

# my_file=open("demo4.text","w")
# my_file.write("Hello java \n")
# my_file.write("where are you")
# print("write operation done")
# my_file.close()

my_file=open("demo4.text","a")
my_file.write("\n")
my_file.write("Hello python \n")
my_file.write("How are you")
print("write operation done")
my_file.close()